import { ObjectId } from "mongodb";

export interface ICieloBin extends Document {
    _id?: ObjectId;
    InitialBin: string;
    FinalBin: string;
    ProductId: number;
    Type: number;
    AllowFallbackWhenChipReadingFails: boolean;
    AllowChargingMoedeiroFromCash: boolean;
    AllowPurchaseWithCompreESaque: boolean;
    AllowOfflineFunctionExceptForEMVCard: boolean;
    AllowTypingCardNumber: boolean;
    MaskCardNumberUsingLast4Digits: boolean;
    MaskCardNumberUsingFirst6AndLast4Digits: boolean;
    AllowPrintCardHolderBalance: boolean;
    AllowDisplayCardHolderBalance: boolean;
    AllowPrintingPartialCardNumberInReceipt: boolean;
    RestrictSaleWithDuplicateValueWhenPostdated: boolean;
    RestrictSaleWithDuplicateValue: boolean;
    RequiresPassword: boolean;
    InterpretsLastDigitOfSecurityCode: boolean;
    RequiresPasswordExceptForEMVCard: boolean;
    EnableAdditionalSecurityCodeOptions_Unreadable_NoCode: boolean;
    RequiresSecurityCodeWhenMagneticTrackIsRead: boolean;
    RequiresSecurityCodeWhenCardNumberIsTyped: boolean;
    RequiresTypingLast4Digits: boolean;
    AllowCaptureOfFirstInstallmentValue: boolean;
    AllowCaptureOfDownpaymentValue: boolean;
    AllowGuaranteeHandling: boolean;
    AllowPostdatingTheFirstInstallmentForSaleAndCDCQuery: boolean;
    AllowPostdating: boolean;
    AllowCDCSale: boolean;
    AllowFinancingByStore: boolean;
    AllowFinancingByCreditCardCompany: boolean;
    ValidateCardTrack1: boolean;
    DoNotValidateCardModule10: boolean;
    CheckExpiryDateWhenCardNumberIsTyped: boolean;
    CheckExpiryDateWhenMagneticTrackIsRead: boolean;
    IssuerId: number;
    SpecificProductId: number;
};
